//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boardreview.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsweredBy
    {
        public int AnsweredByID { get; set; }
        public string BrowserKey { get; set; }
        public int AnswerID { get; set; }
        public int QuestionID { get; set; }
    }
}
